/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoucherRouteImport } from './routes/voucher'
import { Route as TestimoniRouteImport } from './routes/testimoni'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SelectLocationRouteImport } from './routes/select-location'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PickupRouteImport } from './routes/pickup'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LokasiRouteImport } from './routes/lokasi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TableTableNumberRouteImport } from './routes/table.$tableNumber'
import { Route as ReceiptOrderIdRouteImport } from './routes/receipt.$orderId'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as KopipediaArticleIdRouteImport } from './routes/kopipedia.$articleId'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminQrRouteImport } from './routes/_authenticated/admin.qr'

const VoucherRoute = VoucherRouteImport.update({
  id: '/voucher',
  path: '/voucher',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimoniRoute = TestimoniRouteImport.update({
  id: '/testimoni',
  path: '/testimoni',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectLocationRoute = SelectLocationRouteImport.update({
  id: '/select-location',
  path: '/select-location',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupRoute = PickupRouteImport.update({
  id: '/pickup',
  path: '/pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LokasiRoute = LokasiRouteImport.update({
  id: '/lokasi',
  path: '/lokasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableTableNumberRoute = TableTableNumberRouteImport.update({
  id: '/table/$tableNumber',
  path: '/table/$tableNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptOrderIdRoute = ReceiptOrderIdRouteImport.update({
  id: '/receipt/$orderId',
  path: '/receipt/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const KopipediaArticleIdRoute = KopipediaArticleIdRouteImport.update({
  id: '/kopipedia/$articleId',
  path: '/kopipedia/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminQrRoute = AuthenticatedAdminQrRouteImport.update({
  id: '/admin/qr',
  path: '/admin/qr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/lokasi': typeof LokasiRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/pickup': typeof PickupRoute
  '/profile': typeof ProfileRoute
  '/select-location': typeof SelectLocationRoute
  '/settings': typeof SettingsRoute
  '/tentang': typeof TentangRoute
  '/testimoni': typeof TestimoniRoute
  '/voucher': typeof VoucherRoute
  '/admin/login': typeof AdminLoginRoute
  '/kopipedia/$articleId': typeof KopipediaArticleIdRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/receipt/$orderId': typeof ReceiptOrderIdRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
  '/admin/qr': typeof AuthenticatedAdminQrRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/lokasi': typeof LokasiRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/pickup': typeof PickupRoute
  '/profile': typeof ProfileRoute
  '/select-location': typeof SelectLocationRoute
  '/settings': typeof SettingsRoute
  '/tentang': typeof TentangRoute
  '/testimoni': typeof TestimoniRoute
  '/voucher': typeof VoucherRoute
  '/admin/login': typeof AdminLoginRoute
  '/kopipedia/$articleId': typeof KopipediaArticleIdRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/receipt/$orderId': typeof ReceiptOrderIdRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
  '/admin/qr': typeof AuthenticatedAdminQrRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/lokasi': typeof LokasiRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/pickup': typeof PickupRoute
  '/profile': typeof ProfileRoute
  '/select-location': typeof SelectLocationRoute
  '/settings': typeof SettingsRoute
  '/tentang': typeof TentangRoute
  '/testimoni': typeof TestimoniRoute
  '/voucher': typeof VoucherRoute
  '/admin/login': typeof AdminLoginRoute
  '/kopipedia/$articleId': typeof KopipediaArticleIdRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/receipt/$orderId': typeof ReceiptOrderIdRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
  '/_authenticated/admin/qr': typeof AuthenticatedAdminQrRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/delivery'
    | '/login'
    | '/lokasi'
    | '/menu'
    | '/orders'
    | '/pickup'
    | '/profile'
    | '/select-location'
    | '/settings'
    | '/tentang'
    | '/testimoni'
    | '/voucher'
    | '/admin/login'
    | '/kopipedia/$articleId'
    | '/order/$orderId'
    | '/receipt/$orderId'
    | '/table/$tableNumber'
    | '/admin/qr'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/delivery'
    | '/login'
    | '/lokasi'
    | '/menu'
    | '/orders'
    | '/pickup'
    | '/profile'
    | '/select-location'
    | '/settings'
    | '/tentang'
    | '/testimoni'
    | '/voucher'
    | '/admin/login'
    | '/kopipedia/$articleId'
    | '/order/$orderId'
    | '/receipt/$orderId'
    | '/table/$tableNumber'
    | '/admin/qr'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/delivery'
    | '/login'
    | '/lokasi'
    | '/menu'
    | '/orders'
    | '/pickup'
    | '/profile'
    | '/select-location'
    | '/settings'
    | '/tentang'
    | '/testimoni'
    | '/voucher'
    | '/admin/login'
    | '/kopipedia/$articleId'
    | '/order/$orderId'
    | '/receipt/$orderId'
    | '/table/$tableNumber'
    | '/_authenticated/admin/qr'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DeliveryRoute: typeof DeliveryRoute
  LoginRoute: typeof LoginRoute
  LokasiRoute: typeof LokasiRoute
  MenuRoute: typeof MenuRoute
  OrdersRoute: typeof OrdersRoute
  PickupRoute: typeof PickupRoute
  ProfileRoute: typeof ProfileRoute
  SelectLocationRoute: typeof SelectLocationRoute
  SettingsRoute: typeof SettingsRoute
  TentangRoute: typeof TentangRoute
  TestimoniRoute: typeof TestimoniRoute
  VoucherRoute: typeof VoucherRoute
  AdminLoginRoute: typeof AdminLoginRoute
  KopipediaArticleIdRoute: typeof KopipediaArticleIdRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  ReceiptOrderIdRoute: typeof ReceiptOrderIdRoute
  TableTableNumberRoute: typeof TableTableNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voucher': {
      id: '/voucher'
      path: '/voucher'
      fullPath: '/voucher'
      preLoaderRoute: typeof VoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimoni': {
      id: '/testimoni'
      path: '/testimoni'
      fullPath: '/testimoni'
      preLoaderRoute: typeof TestimoniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-location': {
      id: '/select-location'
      path: '/select-location'
      fullPath: '/select-location'
      preLoaderRoute: typeof SelectLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup': {
      id: '/pickup'
      path: '/pickup'
      fullPath: '/pickup'
      preLoaderRoute: typeof PickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lokasi': {
      id: '/lokasi'
      path: '/lokasi'
      fullPath: '/lokasi'
      preLoaderRoute: typeof LokasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$tableNumber': {
      id: '/table/$tableNumber'
      path: '/table/$tableNumber'
      fullPath: '/table/$tableNumber'
      preLoaderRoute: typeof TableTableNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$orderId': {
      id: '/receipt/$orderId'
      path: '/receipt/$orderId'
      fullPath: '/receipt/$orderId'
      preLoaderRoute: typeof ReceiptOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kopipedia/$articleId': {
      id: '/kopipedia/$articleId'
      path: '/kopipedia/$articleId'
      fullPath: '/kopipedia/$articleId'
      preLoaderRoute: typeof KopipediaArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/qr': {
      id: '/_authenticated/admin/qr'
      path: '/admin/qr'
      fullPath: '/admin/qr'
      preLoaderRoute: typeof AuthenticatedAdminQrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminQrRoute: typeof AuthenticatedAdminQrRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminQrRoute: AuthenticatedAdminQrRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DeliveryRoute: DeliveryRoute,
  LoginRoute: LoginRoute,
  LokasiRoute: LokasiRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRoute,
  PickupRoute: PickupRoute,
  ProfileRoute: ProfileRoute,
  SelectLocationRoute: SelectLocationRoute,
  SettingsRoute: SettingsRoute,
  TentangRoute: TentangRoute,
  TestimoniRoute: TestimoniRoute,
  VoucherRoute: VoucherRoute,
  AdminLoginRoute: AdminLoginRoute,
  KopipediaArticleIdRoute: KopipediaArticleIdRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  ReceiptOrderIdRoute: ReceiptOrderIdRoute,
  TableTableNumberRoute: TableTableNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
