/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VouchersRouteImport } from './routes/vouchers'
import { Route as VoucherRouteImport } from './routes/voucher'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as TestimoniRouteImport } from './routes/testimoni'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as SyaratKetentuanRouteImport } from './routes/syarat-ketentuan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SelectLocationRouteImport } from './routes/select-location'
import { Route as PusatBantuanRouteImport } from './routes/pusat-bantuan'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PointsRouteImport } from './routes/points'
import { Route as PickupRouteImport } from './routes/pickup'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NearestOutletsRouteImport } from './routes/nearest-outlets'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LokasiRouteImport } from './routes/lokasi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KopipediaRouteImport } from './routes/kopipedia'
import { Route as KebijakanPrivasiRouteImport } from './routes/kebijakan-privasi'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TableTableNumberRouteImport } from './routes/table.$tableNumber'
import { Route as ReceiptOrderIdRouteImport } from './routes/receipt.$orderId'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as KopipediaArticleIdRouteImport } from './routes/kopipedia.$articleId'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedMasterRouteImport } from './routes/_authenticated/master'
import { Route as AuthenticatedMasterIndexRouteImport } from './routes/_authenticated/master/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedMasterSettingsRouteImport } from './routes/_authenticated/master/settings'
import { Route as AuthenticatedMasterOutletsRouteImport } from './routes/_authenticated/master/outlets'
import { Route as AuthenticatedMasterLoginRouteImport } from './routes/_authenticated/master/login'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin.finance'
import { Route as AuthenticatedAdminDeveloperRouteImport } from './routes/_authenticated/admin.developer'

const VouchersRoute = VouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const VoucherRoute = VoucherRouteImport.update({
  id: '/voucher',
  path: '/voucher',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimoniRoute = TestimoniRouteImport.update({
  id: '/testimoni',
  path: '/testimoni',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const SyaratKetentuanRoute = SyaratKetentuanRouteImport.update({
  id: '/syarat-ketentuan',
  path: '/syarat-ketentuan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectLocationRoute = SelectLocationRouteImport.update({
  id: '/select-location',
  path: '/select-location',
  getParentRoute: () => rootRouteImport,
} as any)
const PusatBantuanRoute = PusatBantuanRouteImport.update({
  id: '/pusat-bantuan',
  path: '/pusat-bantuan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupRoute = PickupRouteImport.update({
  id: '/pickup',
  path: '/pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NearestOutletsRoute = NearestOutletsRouteImport.update({
  id: '/nearest-outlets',
  path: '/nearest-outlets',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LokasiRoute = LokasiRouteImport.update({
  id: '/lokasi',
  path: '/lokasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KopipediaRoute = KopipediaRouteImport.update({
  id: '/kopipedia',
  path: '/kopipedia',
  getParentRoute: () => rootRouteImport,
} as any)
const KebijakanPrivasiRoute = KebijakanPrivasiRouteImport.update({
  id: '/kebijakan-privasi',
  path: '/kebijakan-privasi',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableTableNumberRoute = TableTableNumberRouteImport.update({
  id: '/table/$tableNumber',
  path: '/table/$tableNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptOrderIdRoute = ReceiptOrderIdRouteImport.update({
  id: '/receipt/$orderId',
  path: '/receipt/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const KopipediaArticleIdRoute = KopipediaArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => KopipediaRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMasterRoute = AuthenticatedMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterIndexRoute =
  AuthenticatedMasterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterSettingsRoute =
  AuthenticatedMasterSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterOutletsRoute =
  AuthenticatedMasterOutletsRouteImport.update({
    id: '/outlets',
    path: '/outlets',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterLoginRoute =
  AuthenticatedMasterLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/admin/finance',
    path: '/admin/finance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDeveloperRoute =
  AuthenticatedAdminDeveloperRouteImport.update({
    id: '/admin/developer',
    path: '/admin/developer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/delivery': typeof DeliveryRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kopipedia': typeof KopipediaRouteWithChildren
  '/login': typeof LoginRoute
  '/lokasi': typeof LokasiRoute
  '/menu': typeof MenuRoute
  '/nearest-outlets': typeof NearestOutletsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/pickup': typeof PickupRoute
  '/points': typeof PointsRoute
  '/profile': typeof ProfileRoute
  '/pusat-bantuan': typeof PusatBantuanRoute
  '/select-location': typeof SelectLocationRoute
  '/settings': typeof SettingsRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tentang': typeof TentangRoute
  '/testimoni': typeof TestimoniRoute
  '/tutorial': typeof TutorialRoute
  '/voucher': typeof VoucherRoute
  '/vouchers': typeof VouchersRoute
  '/master': typeof AuthenticatedMasterRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/kopipedia/$articleId': typeof KopipediaArticleIdRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/receipt/$orderId': typeof ReceiptOrderIdRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
  '/admin/developer': typeof AuthenticatedAdminDeveloperRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/master/login': typeof AuthenticatedMasterLoginRoute
  '/master/outlets': typeof AuthenticatedMasterOutletsRoute
  '/master/settings': typeof AuthenticatedMasterSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/master/': typeof AuthenticatedMasterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/delivery': typeof DeliveryRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kopipedia': typeof KopipediaRouteWithChildren
  '/login': typeof LoginRoute
  '/lokasi': typeof LokasiRoute
  '/menu': typeof MenuRoute
  '/nearest-outlets': typeof NearestOutletsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/pickup': typeof PickupRoute
  '/points': typeof PointsRoute
  '/profile': typeof ProfileRoute
  '/pusat-bantuan': typeof PusatBantuanRoute
  '/select-location': typeof SelectLocationRoute
  '/settings': typeof SettingsRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tentang': typeof TentangRoute
  '/testimoni': typeof TestimoniRoute
  '/tutorial': typeof TutorialRoute
  '/voucher': typeof VoucherRoute
  '/vouchers': typeof VouchersRoute
  '/admin/login': typeof AdminLoginRoute
  '/kopipedia/$articleId': typeof KopipediaArticleIdRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/receipt/$orderId': typeof ReceiptOrderIdRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
  '/admin/developer': typeof AuthenticatedAdminDeveloperRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/master/login': typeof AuthenticatedMasterLoginRoute
  '/master/outlets': typeof AuthenticatedMasterOutletsRoute
  '/master/settings': typeof AuthenticatedMasterSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/master': typeof AuthenticatedMasterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai-assistant': typeof AiAssistantRoute
  '/delivery': typeof DeliveryRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kopipedia': typeof KopipediaRouteWithChildren
  '/login': typeof LoginRoute
  '/lokasi': typeof LokasiRoute
  '/menu': typeof MenuRoute
  '/nearest-outlets': typeof NearestOutletsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/pickup': typeof PickupRoute
  '/points': typeof PointsRoute
  '/profile': typeof ProfileRoute
  '/pusat-bantuan': typeof PusatBantuanRoute
  '/select-location': typeof SelectLocationRoute
  '/settings': typeof SettingsRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tentang': typeof TentangRoute
  '/testimoni': typeof TestimoniRoute
  '/tutorial': typeof TutorialRoute
  '/voucher': typeof VoucherRoute
  '/vouchers': typeof VouchersRoute
  '/_authenticated/master': typeof AuthenticatedMasterRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/kopipedia/$articleId': typeof KopipediaArticleIdRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/receipt/$orderId': typeof ReceiptOrderIdRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
  '/_authenticated/admin/developer': typeof AuthenticatedAdminDeveloperRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/master/login': typeof AuthenticatedMasterLoginRoute
  '/_authenticated/master/outlets': typeof AuthenticatedMasterOutletsRoute
  '/_authenticated/master/settings': typeof AuthenticatedMasterSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/master/': typeof AuthenticatedMasterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/delivery'
    | '/kebijakan-privasi'
    | '/kopipedia'
    | '/login'
    | '/lokasi'
    | '/menu'
    | '/nearest-outlets'
    | '/notifications'
    | '/orders'
    | '/pickup'
    | '/points'
    | '/profile'
    | '/pusat-bantuan'
    | '/select-location'
    | '/settings'
    | '/syarat-ketentuan'
    | '/tentang'
    | '/testimoni'
    | '/tutorial'
    | '/voucher'
    | '/vouchers'
    | '/master'
    | '/admin/login'
    | '/kopipedia/$articleId'
    | '/order/$orderId'
    | '/receipt/$orderId'
    | '/table/$tableNumber'
    | '/admin/developer'
    | '/admin/finance'
    | '/master/login'
    | '/master/outlets'
    | '/master/settings'
    | '/admin/'
    | '/master/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/delivery'
    | '/kebijakan-privasi'
    | '/kopipedia'
    | '/login'
    | '/lokasi'
    | '/menu'
    | '/nearest-outlets'
    | '/notifications'
    | '/orders'
    | '/pickup'
    | '/points'
    | '/profile'
    | '/pusat-bantuan'
    | '/select-location'
    | '/settings'
    | '/syarat-ketentuan'
    | '/tentang'
    | '/testimoni'
    | '/tutorial'
    | '/voucher'
    | '/vouchers'
    | '/admin/login'
    | '/kopipedia/$articleId'
    | '/order/$orderId'
    | '/receipt/$orderId'
    | '/table/$tableNumber'
    | '/admin/developer'
    | '/admin/finance'
    | '/master/login'
    | '/master/outlets'
    | '/master/settings'
    | '/admin'
    | '/master'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai-assistant'
    | '/delivery'
    | '/kebijakan-privasi'
    | '/kopipedia'
    | '/login'
    | '/lokasi'
    | '/menu'
    | '/nearest-outlets'
    | '/notifications'
    | '/orders'
    | '/pickup'
    | '/points'
    | '/profile'
    | '/pusat-bantuan'
    | '/select-location'
    | '/settings'
    | '/syarat-ketentuan'
    | '/tentang'
    | '/testimoni'
    | '/tutorial'
    | '/voucher'
    | '/vouchers'
    | '/_authenticated/master'
    | '/admin/login'
    | '/kopipedia/$articleId'
    | '/order/$orderId'
    | '/receipt/$orderId'
    | '/table/$tableNumber'
    | '/_authenticated/admin/developer'
    | '/_authenticated/admin/finance'
    | '/_authenticated/master/login'
    | '/_authenticated/master/outlets'
    | '/_authenticated/master/settings'
    | '/_authenticated/admin/'
    | '/_authenticated/master/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiAssistantRoute: typeof AiAssistantRoute
  DeliveryRoute: typeof DeliveryRoute
  KebijakanPrivasiRoute: typeof KebijakanPrivasiRoute
  KopipediaRoute: typeof KopipediaRouteWithChildren
  LoginRoute: typeof LoginRoute
  LokasiRoute: typeof LokasiRoute
  MenuRoute: typeof MenuRoute
  NearestOutletsRoute: typeof NearestOutletsRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  PickupRoute: typeof PickupRoute
  PointsRoute: typeof PointsRoute
  ProfileRoute: typeof ProfileRoute
  PusatBantuanRoute: typeof PusatBantuanRoute
  SelectLocationRoute: typeof SelectLocationRoute
  SettingsRoute: typeof SettingsRoute
  SyaratKetentuanRoute: typeof SyaratKetentuanRoute
  TentangRoute: typeof TentangRoute
  TestimoniRoute: typeof TestimoniRoute
  TutorialRoute: typeof TutorialRoute
  VoucherRoute: typeof VoucherRoute
  VouchersRoute: typeof VouchersRoute
  AdminLoginRoute: typeof AdminLoginRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  ReceiptOrderIdRoute: typeof ReceiptOrderIdRoute
  TableTableNumberRoute: typeof TableTableNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vouchers': {
      id: '/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof VouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voucher': {
      id: '/voucher'
      path: '/voucher'
      fullPath: '/voucher'
      preLoaderRoute: typeof VoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimoni': {
      id: '/testimoni'
      path: '/testimoni'
      fullPath: '/testimoni'
      preLoaderRoute: typeof TestimoniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syarat-ketentuan': {
      id: '/syarat-ketentuan'
      path: '/syarat-ketentuan'
      fullPath: '/syarat-ketentuan'
      preLoaderRoute: typeof SyaratKetentuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-location': {
      id: '/select-location'
      path: '/select-location'
      fullPath: '/select-location'
      preLoaderRoute: typeof SelectLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pusat-bantuan': {
      id: '/pusat-bantuan'
      path: '/pusat-bantuan'
      fullPath: '/pusat-bantuan'
      preLoaderRoute: typeof PusatBantuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup': {
      id: '/pickup'
      path: '/pickup'
      fullPath: '/pickup'
      preLoaderRoute: typeof PickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearest-outlets': {
      id: '/nearest-outlets'
      path: '/nearest-outlets'
      fullPath: '/nearest-outlets'
      preLoaderRoute: typeof NearestOutletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lokasi': {
      id: '/lokasi'
      path: '/lokasi'
      fullPath: '/lokasi'
      preLoaderRoute: typeof LokasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kopipedia': {
      id: '/kopipedia'
      path: '/kopipedia'
      fullPath: '/kopipedia'
      preLoaderRoute: typeof KopipediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kebijakan-privasi': {
      id: '/kebijakan-privasi'
      path: '/kebijakan-privasi'
      fullPath: '/kebijakan-privasi'
      preLoaderRoute: typeof KebijakanPrivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$tableNumber': {
      id: '/table/$tableNumber'
      path: '/table/$tableNumber'
      fullPath: '/table/$tableNumber'
      preLoaderRoute: typeof TableTableNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$orderId': {
      id: '/receipt/$orderId'
      path: '/receipt/$orderId'
      fullPath: '/receipt/$orderId'
      preLoaderRoute: typeof ReceiptOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kopipedia/$articleId': {
      id: '/kopipedia/$articleId'
      path: '/$articleId'
      fullPath: '/kopipedia/$articleId'
      preLoaderRoute: typeof KopipediaArticleIdRouteImport
      parentRoute: typeof KopipediaRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/master': {
      id: '/_authenticated/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedMasterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/': {
      id: '/_authenticated/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof AuthenticatedMasterIndexRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/settings': {
      id: '/_authenticated/master/settings'
      path: '/settings'
      fullPath: '/master/settings'
      preLoaderRoute: typeof AuthenticatedMasterSettingsRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/outlets': {
      id: '/_authenticated/master/outlets'
      path: '/outlets'
      fullPath: '/master/outlets'
      preLoaderRoute: typeof AuthenticatedMasterOutletsRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/login': {
      id: '/_authenticated/master/login'
      path: '/login'
      fullPath: '/master/login'
      preLoaderRoute: typeof AuthenticatedMasterLoginRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/developer': {
      id: '/_authenticated/admin/developer'
      path: '/admin/developer'
      fullPath: '/admin/developer'
      preLoaderRoute: typeof AuthenticatedAdminDeveloperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedMasterRouteChildren {
  AuthenticatedMasterLoginRoute: typeof AuthenticatedMasterLoginRoute
  AuthenticatedMasterOutletsRoute: typeof AuthenticatedMasterOutletsRoute
  AuthenticatedMasterSettingsRoute: typeof AuthenticatedMasterSettingsRoute
  AuthenticatedMasterIndexRoute: typeof AuthenticatedMasterIndexRoute
}

const AuthenticatedMasterRouteChildren: AuthenticatedMasterRouteChildren = {
  AuthenticatedMasterLoginRoute: AuthenticatedMasterLoginRoute,
  AuthenticatedMasterOutletsRoute: AuthenticatedMasterOutletsRoute,
  AuthenticatedMasterSettingsRoute: AuthenticatedMasterSettingsRoute,
  AuthenticatedMasterIndexRoute: AuthenticatedMasterIndexRoute,
}

const AuthenticatedMasterRouteWithChildren =
  AuthenticatedMasterRoute._addFileChildren(AuthenticatedMasterRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMasterRoute: typeof AuthenticatedMasterRouteWithChildren
  AuthenticatedAdminDeveloperRoute: typeof AuthenticatedAdminDeveloperRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMasterRoute: AuthenticatedMasterRouteWithChildren,
  AuthenticatedAdminDeveloperRoute: AuthenticatedAdminDeveloperRoute,
  AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface KopipediaRouteChildren {
  KopipediaArticleIdRoute: typeof KopipediaArticleIdRoute
}

const KopipediaRouteChildren: KopipediaRouteChildren = {
  KopipediaArticleIdRoute: KopipediaArticleIdRoute,
}

const KopipediaRouteWithChildren = KopipediaRoute._addFileChildren(
  KopipediaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiAssistantRoute: AiAssistantRoute,
  DeliveryRoute: DeliveryRoute,
  KebijakanPrivasiRoute: KebijakanPrivasiRoute,
  KopipediaRoute: KopipediaRouteWithChildren,
  LoginRoute: LoginRoute,
  LokasiRoute: LokasiRoute,
  MenuRoute: MenuRoute,
  NearestOutletsRoute: NearestOutletsRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  PickupRoute: PickupRoute,
  PointsRoute: PointsRoute,
  ProfileRoute: ProfileRoute,
  PusatBantuanRoute: PusatBantuanRoute,
  SelectLocationRoute: SelectLocationRoute,
  SettingsRoute: SettingsRoute,
  SyaratKetentuanRoute: SyaratKetentuanRoute,
  TentangRoute: TentangRoute,
  TestimoniRoute: TestimoniRoute,
  TutorialRoute: TutorialRoute,
  VoucherRoute: VoucherRoute,
  VouchersRoute: VouchersRoute,
  AdminLoginRoute: AdminLoginRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  ReceiptOrderIdRoute: ReceiptOrderIdRoute,
  TableTableNumberRoute: TableTableNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
