CREATE TABLE IF NOT EXISTS public.orders (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  table_number INTEGER NOT NULL CHECK (table_number BETWEEN 1 AND 30),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','cooking','served','paid','cancelled', 'processing', 'completed')),
  total NUMERIC NOT NULL CHECK (total >= 0),
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  branch_id UUID REFERENCES public.branches(id),
  order_type TEXT DEFAULT 'dine-in' CHECK (order_type IN ('dine-in','pickup','delivery','kasir')),
  customer_name TEXT,
  customer_phone TEXT,
  customer_address TEXT,
  customer_lat DOUBLE PRECISION,
  customer_lng DOUBLE PRECISION,
  driver_type TEXT CHECK (driver_type IN ('gosend','grabexpress')),
  estimated_arrival_minutes INTEGER,
  payment_channel TEXT,
  agreed_terms BOOLEAN DEFAULT false,
  needs_bag BOOLEAN DEFAULT false,
  payment_reference TEXT,
  payment_url TEXT,
  payment_method_code TEXT,
  payment_qr_url TEXT,
  payment_instructions JSONB,
  queue_number INTEGER
);
